#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

spawn $env(EXAMPLES_DIR)dir

expect -re {The current working directory is .*/basic-webserver.*\r\n} {
    expect "Set cwd to examples/\r\n" {
        expect "The paths are;\r\n" {
            expect -re {.*dir\.roc.*} {
                exit 0
            }
        }
    }
}

puts stderr "\nError: output was different than expected."
exit 1
