#!/usr/bin/expect

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(TESTS_DIR)server-lifecycle

expect "Listening on <http://127.0.0.1:8000>\r\n" {
    set response [exec curl -sS http://127.0.0.1:8000]

    if {$response ne "context=lifecycle context"} {
        puts stderr "\nExpected lifecycle response 'context=lifecycle context', got '$response'."
        exit 1
    }

    expect "shutdown hook: ApplicationRequested, context: lifecycle context\r\n" {
        expect {
            "shutdown hook:" {
                puts stderr "\nshutdown! ran more than once."
                exit 1
            }
            eof {
                check_exit_and_segfault
            }
        }
    }
}

puts stderr "\nServer lifecycle expect script failed."
exit 1
